/**
 * Stamp the build with the commit it came from.
 *
 * Written into a TypeScript module that the app imports, rather than a
 * file the page fetches at runtime. That distinction is the whole point:
 * the app caches itself in a service worker, so a fetched version file
 * could report a new build while the browser was still running the old
 * JavaScript — which is exactly backwards from what a version label is
 * for. Compiled in, the label can only ever describe the code around it.
 *
 * `src/app/build-info.ts` is generated and gitignored. `npm run build`
 * and `npm test` both run this first, so a fresh clone works.
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const OUT = join(process.cwd(), 'src', 'app', 'build-info.ts');

function git(...args) {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

// GitHub Actions checks out a detached HEAD, so the environment is the
// authority there and git is the fallback for a local build.
const commit = (process.env.GITHUB_SHA || git('rev-parse', 'HEAD') || 'unknown').slice(0, 7);

// A plain count of commits: the "which iteration is this" number, which
// a hash cannot answer at a glance. Shallow CI clones report too few, so
// the workflow fetches full history.
const iteration = Number(git('rev-list', '--count', 'HEAD')) || 0;

const dirty = git('status', '--porcelain') !== '';
const builtAt = new Date().toISOString();

const contents = `/**
 * Generated by scripts/stamp-build.mjs. Do not edit, and do not commit:
 * this file is gitignored and rewritten on every build.
 */

export interface BuildInfo {
  /** Commit count — the iteration number shown in the UI. */
  readonly iteration: number;
  /** Short commit hash of the build. */
  readonly commit: string;
  /** True when the tree had uncommitted changes at build time. */
  readonly dirty: boolean;
  /** ISO timestamp of the build. */
  readonly builtAt: string;
}

export const BUILD: BuildInfo = {
  iteration: ${iteration},
  commit: ${JSON.stringify(commit)},
  dirty: ${dirty},
  builtAt: ${JSON.stringify(builtAt)},
};

/** Short form for a label: \`v247\`, or \`v247+\` for an uncommitted build. */
export const BUILD_LABEL = \`v\${BUILD.iteration}\${BUILD.dirty ? '+' : ''}\`;
`;

mkdirSync(dirname(OUT), { recursive: true });

// Only rewrite when something other than the timestamp changed, so an
// incremental `tsc --watch` is not retriggered by every stamp.
let existing = '';
try {
  existing = readFileSync(OUT, 'utf8');
} catch {
  // First build; nothing to compare against.
}
const strip = (text) => text.replace(/builtAt: "[^"]*"/, '');
if (strip(existing) !== strip(contents)) writeFileSync(OUT, contents);
