/**
 * Stamp the build with the commit it came from.
 *
 * Written into a TypeScript module that the app imports, rather than a
 * file the page fetches at runtime. That distinction is the whole point:
 * the app caches itself in a service worker, so a fetched version file
 * could report a new build while the browser was still running the old
 * JavaScript — which is exactly backwards from what a version label is
 * for. Compiled in, the label can only ever describe the code around it.
 *
 * `src/app/build-info.ts` is generated and gitignored. `npm run build`
 * and `npm test` both run this first, so a fresh clone works.
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const OUT = join(process.cwd(), 'src', 'app', 'build-info.ts');

function git(...args) {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

// GitHub Actions checks out a detached HEAD, so the environment is the
// authority there and git is the fallback for a local build.
const commit = (process.env.GITHUB_SHA || git('rev-parse', 'HEAD') || 'unknown').slice(0, 7);

// A plain count of commits, used as the patch number. Shallow CI clones
// report too few, so the workflow fetches full history.
const build = Number(git('rev-list', '--count', 'HEAD')) || 0;

// major.minor come from package.json, so bumping either is an edit to the
// file that already declares the version rather than a constant hidden in
// a build script. The patch is the commit count, which makes every build
// distinct and ordered without anyone having to remember to increment it.
let major = 0;
let minor = 0;
try {
  const pkg = JSON.parse(readFileSync(join(process.cwd(), 'package.json'), 'utf8'));
  const parts = String(pkg.version ?? '0.0.0').split('.');
  major = Number(parts[0]) || 0;
  minor = Number(parts[1]) || 0;
} catch {
  // A missing or unreadable package.json leaves 0.0, which is honest.
}

const version = `${major}.${minor}.${build}`;

const dirty = git('status', '--porcelain') !== '';
const builtAt = new Date().toISOString();

const contents = `/**
 * Generated by scripts/stamp-build.mjs. Do not edit, and do not commit:
 * this file is gitignored and rewritten on every build.
 */

export interface BuildInfo {
  /** Dotted version: major.minor from package.json, patch = commit count. */
  readonly version: string;
  /** Commit count, i.e. the patch number on its own. */
  readonly build: number;
  /** Short commit hash of the build. */
  readonly commit: string;
  /** True when the tree had uncommitted changes at build time. */
  readonly dirty: boolean;
  /** ISO timestamp of the build. */
  readonly builtAt: string;
}

export const BUILD: BuildInfo = {
  version: ${JSON.stringify(version)},
  build: ${build},
  commit: ${JSON.stringify(commit)},
  dirty: ${dirty},
  builtAt: ${JSON.stringify(builtAt)},
};

/** The label shown in the UI: \`v0.1.29\`, or \`v0.1.29+\` when built dirty. */
export const BUILD_LABEL = \`v\${BUILD.version}\${BUILD.dirty ? '+' : ''}\`;
`;

mkdirSync(dirname(OUT), { recursive: true });

// Only rewrite when something other than the timestamp changed, so an
// incremental `tsc --watch` is not retriggered by every stamp.
let existing = '';
try {
  existing = readFileSync(OUT, 'utf8');
} catch {
  // First build; nothing to compare against.
}
const strip = (text) => text.replace(/builtAt: "[^"]*"/, '');
if (strip(existing) !== strip(contents)) writeFileSync(OUT, contents);
